[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "shiplibrary"
version = "0.1.0"
description = "My package has module_file and init"

[tool.poetry.dependencies]
python = "3.10.8"
requests = ""
poetry-core = "^1.0.0"
